float32 pos_inert_x
float32 pos_inert_y
float32 pos_inert_z

float32 local_r
float32 local_az
float32 local_el

float32 roll
float32 pitch
float32 yaw

float32 roll_s
float32 pitch_s
float32 yaw_s

float32 L1_ratio
float32 L1_K
float32 L1_arc

float32 R_arc
float32 PC_arc
float32 PW_arc
float32 CW_arc

float32 heading_gs
float32 ber_c
float32 ber_ref

float32 eta
float32 a_lat
float32 target_roll

float32 param_EL
float32 param_AZ
float32 param_RAD
float32 param_DAMP
float32 param_PER
float32 param_P_ROLL
float32 param_BANK
float32 param_DIR
float32 param_SEL

float32 reserve_0
float32 reserve_1
float32 reserve_2
float32 reserve_3
float32 reserve_4
float32 reserve_5
float32 reserve_6
float32 reserve_7
float32 reserve_8
float32 reserve_9


# TOPICS traction_status

